# -*- coding: utf-8 -*-
"""A perceived loudness (PLdB) calculator.

PyLdB implements Stevens' Mark VII procedure for the calculation of the
perceived loudness of a pressure signature.

Classes
-------
PyLdB
    Object-oriented calculator for importing, preprocessing, analyzing, and
    post-processing pressure signatures.
LoudnessResults
    Container returned by :meth:`PyLdB.calculate` and exposed as
    ``PyLdB.loudness``.

Routine Listings
----------------
PyLdB.calculate(...)
    Calculates PLdB and acoustic post-processing metrics, then stores them on
    ``object.loudness``.
PyLdB.perceived_loudness(...)
    Calculates perceived loudness in PLdB using Stevens' Mark VII procedure.
PyLdB.import_signature(filename[, header_lines, delimiter])
    Imports a two-column time and pressure signature from a file.
PyLdB.window(len_window)
    Applies a Hanning window to the active pressure signature.
PyLdB.padding(n_pad_points)
    Applies zero padding to the front and rear of the active signature.
PyLdB._power_spectrum()
    Performs an FFT on the active pressure signature and generates a one-sided
    power spectrum.
PyLdB._power_interp(freq, power)
    Interpolates power data to match frequency band boundaries.
PyLdB._sound_pressure_levels(freq, power)
    Calculates the sound pressure level of each frequency band.
PyLdB._equivalent_loudness(loudness)
    Calculates equivalent loudness values.
PyLdB._calc_total_loudness(L_eq)
    Uses table values to look up and interpolate a summation factor and sone
    values to calculate total loudness for a signature.

See Also
--------
numpy.interp : Linear interpolation for arrays.
numpy.hanning : Calculates a Hanning window given a number of points.
numpy.pad : Zero-pads an array.
numpy.fft.rfft : Real-input fast Fourier transform (FFT) routine.
numpy.fft.rfftfreq : Generates the one-sided frequency range for an FFT.
numpy.argsort : Returns indices to sort an array.
numpy.nonzero : Returns non-zero elements in an array subject to conditions.
numpy.trapz : Performs trapezoidal numerical integration.

Notes
-----
The pyldb module utilizes the Mark VII procedure for the calculation of
perceived loudness created by Stevens. The procedure works by first importing
time and pressure data, which is windowed and zero-padded prior to performing
a frequency analysis via an FFT. From the frequency analysis, a one-sided
power spectrum is created, which allows for the calculation of the energy
contained in one-third octave frequency bands for the pressure signature. The
energy is found by integrating the power spectrum using a trapezoidal rule.
This energy can be transformed into a sound pressure level measured in decibels
for each frequency band. The sound pressure levels are then converted to an
equivalent loudness value using equal-sone contours generated by Stevens. Using
data tabulated by Stevens, a total loudness in units of sones is calculated,
which is then transformed into perceived loudness using a power law developed
by Stevens.

References
----------
Stevens, S., "Perceived level of noise by Mark VII and decibels (E),"
The Journal of the Acoustical Society of America, Vol. 51, No. 2B, 1972,
pp. 575-601.

Jackson, G., and Leventhall, H., "Calculation of the perceived level of noise
(PLdB) using Stevens' method (Mark VII)," Applied Acoustics, Vol. 6, No. 1,
1973, pp. 23-34.

Shepherd, K. P., and Sullivan, B. M., "A loudness calculation procedure
applied to shaped sonic booms," 1991.

Johnson, D., and Robinson, D., "Procedure for calculating the loudness of
sonic bangs," Acta Acustica united with Acustica, Vol. 21, No. 6, 1969,
pp. 307-318.

Examples
--------
>>> from pyldb import PyLdB
>>> calculator = PyLdB("misc/panair_r1.sig", header_lines=3)
>>> results = calculator.calculate(pad_front=6, pad_rear=6, len_window=800)
>>> print(results.pldb)
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
from scipy import signal

from .acoustics import alphabet_weighted_levels, dnl, equivalent, fidell_ctl


@dataclass
class LoudnessResults:
    """Container for calculated loudness metrics.

    Attributes
    ----------
    pldb : float
        Perceived loudness in PLdB calculated with Stevens' Mark VII method.
    ctl : float
        Fidell CTL high-annoyance response probability for the calculated PLdB.
        This is also available as ``ctl_response`` for clarity.
    community_tolerance_level : float or None
        Community Tolerance Level used to calculate ``ctl``. When ``a_star`` is
        supplied instead of ``ctl``, this value is derived from ``a_star`` and
        ``growth``.
    dnl : float
        Day-night average level calculated from the supplied day and night
        loudness values.
    equivalent_loudness : float
        Energy-equivalent loudness level calculated from the supplied loudness
        sequence.
    alphabet_weighted_loudnesses : dict
        Overall A-, B-, C-, and D-weighted levels keyed as ``"a"``, ``"b"``,
        ``"c"``, and ``"d"``.
    """

    pldb: float
    ctl: float
    community_tolerance_level: Optional[float]
    dnl: float
    equivalent_loudness: float
    alphabet_weighted_loudnesses: Dict[str, float]

    @property
    def ctl_response(self) -> float:
        return self.ctl

    @property
    def a_weighted_loudness(self) -> float:
        return self.alphabet_weighted_loudnesses["a"]

    @property
    def b_weighted_loudness(self) -> float:
        return self.alphabet_weighted_loudnesses["b"]

    @property
    def c_weighted_loudness(self) -> float:
        return self.alphabet_weighted_loudnesses["c"]

    @property
    def d_weighted_loudness(self) -> float:
        return self.alphabet_weighted_loudnesses["d"]


@dataclass
class SensitivityResults:
    """Container for calibrated wavelet sensitivity diagnostics."""

    global_pldb: float
    time_s: np.ndarray
    band_centers_hz: np.ndarray
    fft_band_energy: np.ndarray
    local_energy: np.ndarray
    sone_map: np.ndarray
    local_pldb: np.ndarray
    top_buckets: Tuple[Dict[str, float], ...]


class PyLdB:
    """Object-oriented perceived loudness calculator.

    The class owns the pressure signature, the Stevens table data, the
    intermediate spectral quantities, and the final acoustic result object.
    A signature can be supplied at construction time, imported later with
    :meth:`import_signature`, or passed directly to :meth:`calculate` or
    :meth:`perceived_loudness`.

    Parameters
    ----------
    signature_file : str or pathlib.Path, optional
        Path to a two-column signature file. PANAIR ``.sig`` files can be read by
        passing ``header_lines=3``.
    time : array_like, optional
        Time samples in milliseconds.
    pressure : array_like, optional
        Pressure samples in psf.
    header_lines : int, optional
        Number of header lines to skip when ``signature_file`` is supplied.
    delimiter : str, optional
        Delimiter passed to :func:`numpy.genfromtxt`.

    Attributes
    ----------
    sig_time_ms : numpy.ndarray or None
        Active time signature in milliseconds.
    sig_pressure_psf : numpy.ndarray or None
        Active pressure signature in pounds per square foot.
    loudness : LoudnessResults or None
        Result container populated by :meth:`calculate`.

    Examples
    --------
    >>> from pyldb import PyLdB
    >>> calculator = PyLdB("misc/panair_r1.sig", header_lines=3)
    >>> calculator.calculate()
    >>> calculator.loudness.pldb
    """

    ref_pressure_psf = 2.900755e-9 * 144.0  # 20 micro-Pa converted to psf
    ref_time_s = 0.07

    def __init__(
        self,
        signature_file: Optional[str | Path] = None,
        *,
        time: Optional[np.ndarray] = None,
        pressure: Optional[np.ndarray] = None,
        header_lines: int = 0,
        delimiter: Optional[str] = None,
        pad_front: int = 1,
        pad_rear: int = 1,
        len_window: int = 800,
    ) -> None:
        self._initialize_table_data()
        self.clear_signature()
        self.clear_results()
        self.pad_front = 1
        self.pad_rear = 1
        self.len_window = 800
        self.configure(pad_front=pad_front, pad_rear=pad_rear, len_window=len_window)

        if signature_file is not None:
            self.import_signature(signature_file, header_lines=header_lines, delimiter=delimiter)
        elif time is not None or pressure is not None:
            if time is None or pressure is None:
                raise ValueError("Both time and pressure must be supplied together.")
            self.set_signature(time, pressure)

    def clear_signature(self) -> None:
        """Remove the currently loaded signature.

        This clears the active arrays, the preserved source arrays used for
        repeatable recalculation, timing metadata, and preprocessing flags.
        Table data loaded at construction time is not affected.
        """

        self.sig_time_ms: Optional[np.ndarray] = None
        self.sig_pressure_psf: Optional[np.ndarray] = None
        self._source_time_ms: Optional[np.ndarray] = None
        self._source_pressure_psf: Optional[np.ndarray] = None
        self.dt_ms: Optional[float] = None
        self.dt_s: Optional[float] = None
        self.freq_s: Optional[float] = None
        self.n_data_points = 0
        self.windowed_signal = False
        self.S_1 = 1.0
        self.S_1sq = 1.0
        self.S_2 = 1.0

    def clear_results(self) -> None:
        """Remove previously calculated intermediate and final results.

        This clears spectral data, band energies, band sound pressure levels,
        equivalent loudness values, sones, PLdB, and the ``loudness`` result
        object. The active pressure signature is not changed.
        """

        self.frequency_hz: Optional[np.ndarray] = None
        self.power_spectrum: Optional[np.ndarray] = None
        self.band_energy: Optional[np.ndarray] = None
        self.sound_pressure_level: Optional[np.ndarray] = None
        self.equivalent_loudness: Optional[np.ndarray] = None
        self.sones: Optional[np.ndarray] = None
        self.total_loudness_sones: Optional[float] = None
        self.perceived_loudness_pldb: Optional[float] = None
        self.loudness: Optional[LoudnessResults] = None
        self.sensitivity_results: Optional[SensitivityResults] = None

    def configure(
        self,
        *,
        pad_front: Optional[int] = None,
        pad_rear: Optional[int] = None,
        len_window: Optional[int] = None,
    ) -> "PyLdB":
        """Update reusable preprocessing settings for future calculations."""

        if pad_front is not None:
            if pad_front < 0:
                raise ValueError("Front padding multiplier must be non-negative.")
            self.pad_front = int(pad_front)
        if pad_rear is not None:
            if pad_rear < 0:
                raise ValueError("Rear padding multiplier must be non-negative.")
            self.pad_rear = int(pad_rear)
        if len_window is not None:
            if len_window < 0:
                raise ValueError("Window length must be non-negative.")
            self.len_window = int(len_window)
        return self

    def import_signature(
        self,
        filename: str | Path,
        *,
        header_lines: int = 0,
        delimiter: Optional[str] = None,
    ) -> "PyLdB":
        r"""Import time and pressure data from a file into this calculator.

        Any file type that is compatible with :func:`numpy.genfromtxt` can be
        used with this method. The time data should be contained in the
        left-most column of the file, and the pressure data should be contained
        in the next column. Header lines should be skipped using the
        ``header_lines`` parameter.

        Parameters
        ----------
        filename : str or pathlib.Path
            Name of the file from which the time and pressure data will be
            imported.
        header_lines : int, optional
            Number of lines containing header information to skip before
            reading numeric data.
        delimiter : str, optional
            Delimiter passed to :func:`numpy.genfromtxt`.

        Returns
        -------
        PyLdB
            The calculator instance, allowing method chaining.

        Examples
        --------
        >>> from pyldb import PyLdB
        >>> calculator = PyLdB()
        >>> calculator.import_signature("misc/panair_r1.sig", header_lines=3)
        """

        sig_data = np.genfromtxt(filename, skip_header=header_lines, delimiter=delimiter)
        if sig_data.ndim != 2 or sig_data.shape[1] < 2:
            raise ValueError("Signature files must contain at least two numeric columns.")
        return self.set_signature(sig_data[:, 0], sig_data[:, 1])

    def _import_sig(
        self,
        filename: str | Path,
        header_lines: int = 0,
        delimiter: Optional[str] = None,
    ) -> "PyLdB":
        """Backward-compatible alias for :meth:`import_signature`."""

        return self.import_signature(filename, header_lines=header_lines, delimiter=delimiter)

    def set_signature(self, time: np.ndarray, pressure: np.ndarray) -> "PyLdB":
        """Set the active pressure signature from arrays.

        Parameters
        ----------
        time : array_like
            Time signature in milliseconds. Values must be one-dimensional,
            strictly increasing, and evenly spaced.
        pressure : array_like
            Pressure signature in pounds per square foot. It must be
            one-dimensional and have the same number of points as ``time``.

        Returns
        -------
        PyLdB
            The calculator instance, allowing method chaining.
        """

        time_array = np.asarray(time, dtype=float)
        pressure_array = np.asarray(pressure, dtype=float)

        if time_array.ndim != 1 or pressure_array.ndim != 1:
            raise ValueError("Time and pressure must be one-dimensional arrays.")
        if len(time_array) != len(pressure_array):
            raise ValueError("Time and pressure arrays must have the same length.")
        if len(time_array) < 2:
            raise ValueError("At least two signature points are required.")

        dt = np.diff(time_array)
        if not np.all(dt > 0.0):
            raise ValueError("Time values must be strictly increasing.")
        if not np.allclose(dt, dt[0]):
            raise ValueError("Time samples must be evenly spaced.")

        self.sig_time_ms = time_array.copy()
        self.sig_pressure_psf = pressure_array.copy()
        self._source_time_ms = time_array.copy()
        self._source_pressure_psf = pressure_array.copy()
        self.dt_ms = float(dt[0])
        self.dt_s = self.dt_ms * 1.0e-3
        self.freq_s = 1.0 / self.dt_s
        self.n_data_points = len(self.sig_pressure_psf)
        self.windowed_signal = False
        self.clear_results()
        return self

    def perceived_loudness(
        self,
        time: Optional[np.ndarray] = None,
        pressure: Optional[np.ndarray] = None,
        *,
        signature_file: Optional[str | Path] = None,
        header_lines: int = 0,
        delimiter: Optional[str] = None,
        pad_front: Optional[int] = None,
        pad_rear: Optional[int] = None,
        len_window: Optional[int] = None,
        print_results: bool = False,
        results_dir: str | Path = "PyLdB_Results",
    ) -> float:
        r"""Calculate perceived loudness using Stevens' Mark VII procedure.

        This method encapsulates all of the calculation steps required to return
        a perceived loudness value given time and pressure arrays, an imported
        signature file, or the signature already stored on the object. The
        pressure signature is first windowed using a Hanning window to ensure a
        complete cycle can be formed for use in a fast Fourier transform (FFT).
        Next, the time and pressure arrays are zero-padded to increase the
        resolution of the FFT output.

        Using the windowed and zero-padded pressure and time arrays, a
        one-sided power spectrum is produced. The energy in the power spectrum
        is calculated using trapezoidal numerical integration. The energy is
        then used to find a sound pressure level in decibels for one-third
        octave frequency bands loaded from the package tables.

        Stevens' Mark VII algorithm transforms the sound pressure levels for
        each frequency band into an equivalent loudness value with a 3150 Hz
        reference frequency. Equivalent loudness values are then converted to
        sones with tabulated data from Stevens. A summation parameter is also
        found using tabulated data. Finally, a summation rule is used to find
        total loudness, which is transformed into perceived loudness in PLdB.

        Parameters
        ----------
        time : array_like, optional
            Time signature in milliseconds. If supplied, ``pressure`` must also
            be supplied and both arrays replace the active signature.
        pressure : array_like, optional
            Pressure signature in pounds per square foot.
        signature_file : str or pathlib.Path, optional
            Signature file to import before calculating.
        header_lines : int, optional
            Number of file header lines to skip when ``signature_file`` is
            supplied.
        delimiter : str, optional
            Delimiter passed to :func:`numpy.genfromtxt` when importing a file.
        pad_front : int, optional
            Defaults to 1. Multiplier specifying the number of zero-padding
            points added to the front of the arrays. For example, if
            ``pad_front=10``, the number of zeros added to the front is ten
            times the original signature length.
        pad_rear : int, optional
            Defaults to 1. Multiplier specifying the number of zero-padding
            points added to the rear of the arrays.
        len_window : int, optional
            Defaults to 800 points. Number of points over which the Hanning
            window is applied on both the front and rear of the signal. The
            first ``len_window`` pressure values are multiplied by the first
            half of a ``2 * len_window`` Hanning window, and the last
            ``len_window`` pressure values are multiplied by the second half.
        print_results : bool, optional
            Defaults to False. If True, writes the padded/windowed signature,
            power spectrum, sound pressure levels, equivalent loudness values,
            and sones to ``results_dir``.
        results_dir : str or pathlib.Path, optional
            Directory where calculation intermediates are written when
            ``print_results`` is True.

        Returns
        -------
        pldb : float
            Perceived loudness in units of PLdB.

        Examples
        --------
        >>> from pyldb import PyLdB
        >>> calculator = PyLdB("misc/panair_r1.sig", header_lines=3)
        >>> pldb = calculator.perceived_loudness(pad_front=6, pad_rear=6)
        """

        self._load_or_require_signature(
            time=time,
            pressure=pressure,
            signature_file=signature_file,
            header_lines=header_lines,
            delimiter=delimiter,
        )
        self._prepare_working_signature(
            pad_front=pad_front,
            pad_rear=pad_rear,
            len_window=len_window,
        )
        self._run_mark_vii()

        if print_results:
            self.write_results(results_dir)

        return self.perceived_loudness_pldb

    def perceivedloudness(self, *args, **kwargs) -> float:
        """Backward-compatible alias for :meth:`perceived_loudness`."""

        return self.perceived_loudness(*args, **kwargs)

    def calculate(
        self,
        time: Optional[np.ndarray] = None,
        pressure: Optional[np.ndarray] = None,
        *,
        signature_file: Optional[str | Path] = None,
        header_lines: int = 0,
        delimiter: Optional[str] = None,
        pad_front: Optional[int] = None,
        pad_rear: Optional[int] = None,
        len_window: Optional[int] = None,
        ctl: Optional[float] = 75.0,
        a_star: Optional[float] = None,
        growth: float = 0.3,
        day_loudness=None,
        night_loudness=None,
        equivalent_loudnesses=None,
        print_results: bool = False,
        results_dir: str | Path = "PyLdB_Results",
    ) -> LoudnessResults:
        """Calculate PLdB and acoustic post-processing metrics.

        This method first calls :meth:`perceived_loudness`, then uses the
        acoustic helper methods in :mod:`pyldb.acoustics` to calculate Community
        Tolerance Level response, day-night average level, energy-equivalent
        loudness, and A-, B-, C-, and D-weighted overall loudnesses. Results are
        stored on ``self.loudness`` and returned.

        Parameters
        ----------
        time, pressure, signature_file, header_lines, delimiter, pad_front,
        pad_rear, len_window, print_results, results_dir
            Passed through to :meth:`perceived_loudness`.
        ctl : float or None, optional
            Community Tolerance Level used by the Fidell response model.
            Defaults to 75.0. If None, ``a_star`` must be supplied.
        a_star : float or None, optional
            Fidell model intercept used to derive CTL when ``ctl`` is None.
        growth : float, optional
            Fidell model growth rate. The default of 0.3 is commonly used for
            subsonic aircraft noise.
        day_loudness : scalar or array_like, optional
            Daytime loudness levels for DNL. Scalars are repeated for 15 daytime
            hours. Arrays must contain 15 values.
        night_loudness : scalar or array_like, optional
            Nighttime loudness levels for DNL. Scalars are repeated for 9
            nighttime hours. Arrays must contain 9 values.
        equivalent_loudnesses : scalar or array_like, optional
            Loudness values used to calculate energy-equivalent loudness. If
            omitted, the calculated PLdB is used.

        Returns
        -------
        LoudnessResults
            Result container also available as ``self.loudness``.
        """

        pldb = self.perceived_loudness(
            time=time,
            pressure=pressure,
            signature_file=signature_file,
            header_lines=header_lines,
            delimiter=delimiter,
            pad_front=pad_front,
            pad_rear=pad_rear,
            len_window=len_window,
            print_results=print_results,
            results_dir=results_dir,
        )

        self.loudness = self._build_loudness_results(
            pldb=pldb,
            ctl=ctl,
            a_star=a_star,
            growth=growth,
            day_loudness=pldb if day_loudness is None else day_loudness,
            night_loudness=pldb if night_loudness is None else night_loudness,
            equivalent_loudnesses=pldb if equivalent_loudnesses is None else equivalent_loudnesses,
        )
        return self.loudness

    def sensitivity(
        self,
        *,
        top_n: int = 20,
        pad_front: Optional[int] = None,
        pad_rear: Optional[int] = None,
        len_window: Optional[int] = None,
    ) -> SensitivityResults:
        """Calculate calibrated wavelet sensitivity diagnostics.

        The standard FFT Mark VII calculation is performed first. Morlet CWT
        energy is then calibrated band-by-band so each localized band energy
        time history integrates to the corresponding FFT band energy.
        """

        if top_n < 0:
            raise ValueError("top_n must be non-negative.")

        self._load_or_require_signature()
        self._prepare_working_signature(
            pad_front=pad_front,
            pad_rear=pad_rear,
            len_window=len_window,
        )
        global_pldb = self._run_mark_vii()
        time_s = self.sig_time_ms * 1.0e-3
        raw_energy = self._wavelet_local_energy()
        local_energy = self._calibrate_local_energy(raw_energy, time_s, self.band_energy)
        local_spl = self._sound_pressure_level_from_energy(local_energy)
        sone_map = self._sones_from_equivalent_loudness(self._equivalent_loudness(local_spl))
        local_pldb = self._pldb_from_sones(sone_map)
        top_buckets = self._top_sensitivity_buckets(time_s, local_energy, sone_map, local_pldb, top_n)

        self.sensitivity_results = SensitivityResults(
            global_pldb=global_pldb,
            time_s=time_s.copy(),
            band_centers_hz=self.freq_band_center.copy(),
            fft_band_energy=self.band_energy.copy(),
            local_energy=local_energy,
            sone_map=sone_map,
            local_pldb=local_pldb,
            top_buckets=top_buckets,
        )
        return self.sensitivity_results

    def window(self, len_window: int) -> "PyLdB":
        """Apply a symmetric Hanning window to the active pressure signature.

        Parameters
        ----------
        len_window : int
            Number of points over which the Hanning window is applied on both
            the front and rear of the pressure signature.

        Returns
        -------
        PyLdB
            The calculator instance, allowing method chaining.
        """

        self._require_pressure()
        self.n_data_points = len(self.sig_pressure_psf)
        if len_window < 0:
            raise ValueError("Window length must be non-negative.")
        if len_window == 0:
            return self
        if 2 * len_window > self.n_data_points:
            raise ValueError("Window length cannot exceed half the signature length.")

        win = np.hanning(len_window * 2)
        self.sig_pressure_psf[:len_window] *= win[:len_window]
        self.sig_pressure_psf[-len_window:] *= win[len_window:]
        self.windowed_signal = True
        self.S_1 = float(np.sum(win))
        self.S_1sq = self.S_1**2
        self.S_2 = float(np.sum(np.square(win)))
        return self

    def padding(
        self,
        n_pad_points: Optional[int] = None,
        *,
        n_front_points: Optional[int] = None,
        n_rear_points: Optional[int] = None,
    ) -> "PyLdB":
        """Zero-pad the active signature and extend the time array.

        Passing ``n_pad_points`` pads both sides equally, matching the previous
        public method. ``n_front_points`` and ``n_rear_points`` may be used for
        asymmetric padding.

        Parameters
        ----------
        n_pad_points : int, optional
            Number of zeros added to both the front and rear of the pressure
            signature.
        n_front_points : int, optional
            Number of zeros added to the front of the pressure signature.
        n_rear_points : int, optional
            Number of zeros added to the rear of the pressure signature.

        Returns
        -------
        PyLdB
            The calculator instance, allowing method chaining.
        """

        self._require_signature()
        if n_pad_points is not None:
            n_front_points = n_pad_points
            n_rear_points = n_pad_points
        if n_front_points is None:
            n_front_points = 0
        if n_rear_points is None:
            n_rear_points = 0
        if n_front_points < 0 or n_rear_points < 0:
            raise ValueError("Padding point counts must be non-negative.")

        n_front_points = int(n_front_points)
        n_rear_points = int(n_rear_points)
        dt = self.dt_ms

        original_time = self.sig_time_ms
        original_pressure = self.sig_pressure_psf
        front_time = np.arange(n_front_points, dtype=float) * dt
        shifted_time = original_time + n_front_points * dt
        rear_start = shifted_time[-1] + dt
        rear_time = rear_start + np.arange(n_rear_points, dtype=float) * dt

        self.sig_time_ms = np.concatenate((front_time, shifted_time, rear_time))
        self.sig_pressure_psf = np.pad(original_pressure, (n_front_points, n_rear_points), "constant")
        self.n_data_points = len(self.sig_pressure_psf)
        self.clear_results()
        return self

    def write_results(self, results_dir: str | Path = "PyLdB_Results") -> None:
        """Write signature, spectrum, and loudness intermediates to text files.

        Parameters
        ----------
        results_dir : str or pathlib.Path, optional
            Output directory. It is created if it does not already exist.
        """

        if self.perceived_loudness_pldb is None:
            raise RuntimeError("No calculated results are available to write.")

        directory = Path(results_dir)
        directory.mkdir(parents=True, exist_ok=True)
        np.savetxt(directory / "final_sig", np.array([self.sig_time_ms, self.sig_pressure_psf]).T)
        np.savetxt(directory / "power_spec", np.array([self.frequency_hz, self.power_spectrum]).T)
        np.savetxt(directory / "sound_pressure_levels", np.array([self.freq_band_center, self.sound_pressure_level]).T)
        np.savetxt(directory / "equivalent_loudness", np.array([self.freq_band_center, self.equivalent_loudness]).T)
        np.savetxt(directory / "sones", np.array([self.freq_band_center, self.sones]).T)

    def _initialize_table_data(self) -> None:
        """Load Stevens loudness and frequency-band tables from disk."""

        base_dir = Path(__file__).resolve().parent
        tables_dir = base_dir.parent / "tables"

        equiv_loudness_sones_data = np.genfromtxt(tables_dir / "L_eq_v_sones.csv", delimiter=",", skip_header=1)
        self.equiv_loudness_sones_data = equiv_loudness_sones_data
        self.equiv_loudness_table_indep = equiv_loudness_sones_data[:, 0]
        self.sones_equiv_loudness_table = equiv_loudness_sones_data[:, 1]
        self.num_equiv_loudness_vals = len(self.equiv_loudness_table_indep)

        sones_sum_factor_data = np.genfromtxt(tables_dir / "sones_v_sumf.csv", delimiter=",", skip_header=1)
        self.sones_sum_factor_data = sones_sum_factor_data
        self.sones_table_indep = sones_sum_factor_data[:, 0]
        self.sum_factor_table = sones_sum_factor_data[:, 1]
        self.num_sum_factors = len(self.sones_table_indep)

        freq_band_data = np.genfromtxt(tables_dir / "freq_bands.csv", delimiter=",", skip_header=1)
        self.freq_band_data = freq_band_data
        self.freq_band_center = freq_band_data[:, 0]
        self.freq_band_lower_lim = freq_band_data[:, 1]
        self.freq_band_upper_lim = freq_band_data[:, 2]
        self.num_freq_bands = len(self.freq_band_center)

    def _power_spectrum(self) -> Tuple[np.ndarray, np.ndarray]:
        """Generate a one-sided power spectrum for the active signature.

        The units for time are milliseconds, and the units for pressure are
        pounds per square foot. The FFT spacing convention intentionally
        preserves the original PyLdB implementation so historical regression
        values are reproduced.
        """

        self._require_signature()

        # Preserve the original PyLdB FFT spacing convention. The padded time
        # vector is inclusive at both ends, so this uses duration / N rather
        # than the raw sample spacing.
        dt_s = ((self.sig_time_ms[-1] - self.sig_time_ms[0]) / self.n_data_points) * 1.0e-3
        fft_values = np.fft.rfft(self.sig_pressure_psf)
        freq = np.fft.rfftfreq(self.n_data_points, d=dt_s)
        power = np.abs(fft_values) ** 2 * dt_s**2

        if len(power) > 2:
            power[1:-1] *= 2.0
        elif len(power) == 2 and self.n_data_points % 2:
            power[1] *= 2.0

        return self._power_interp(freq, power)

    def _power_interp(self, freq: np.ndarray, power: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        """Interpolate power values at one-third-octave band boundaries."""

        interp_freq = np.append(self.freq_band_lower_lim, self.freq_band_upper_lim[-1])
        interp_power = np.interp(interp_freq, freq, power)

        full_freq = np.concatenate((freq, interp_freq))
        full_power = np.concatenate((power, interp_power))
        order = np.argsort(full_freq, kind="mergesort")
        return full_freq[order], full_power[order]

    def _sound_pressure_levels(self, freq: np.ndarray, power: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        """Calculate band energy and sound pressure levels.

        Power is integrated within each one-third-octave band using the
        trapezoidal rule. Band energy is divided by the 0.07 second human
        auditory response time before conversion to decibels.
        """

        energy = np.zeros(self.num_freq_bands)

        for j in range(self.num_freq_bands):
            section = np.nonzero((self.freq_band_lower_lim[j] <= freq) & (freq <= self.freq_band_upper_lim[j]))[0]
            if len(section) > 1:
                energy[j] = np.trapz(power[section], x=freq[section])

        energy /= self.ref_time_s
        return energy, self._sound_pressure_level_from_energy(energy)

    def _equivalent_loudness(self, loudness: np.ndarray) -> np.ndarray:
        """Transform band sound pressure levels to equivalent loudness values."""

        loudness = np.asarray(loudness, dtype=float)
        L_eq = np.zeros_like(loudness)

        for i in range(self.num_freq_bands):
            band_loudness = loudness[i]
            if i > 39:
                L_eq[i] = band_loudness + 4.0 * (39.0 - i)
            elif 35 <= i <= 39:
                L_eq[i] = band_loudness
            elif 32 <= i <= 34:
                L_eq[i] = band_loudness - 2.0 * (35.0 - i)
            elif 26 < i <= 31:
                L_eq[i] = band_loudness - 8.0
            elif 20 <= i <= 26:
                lower_limit = 76.0 + 1.5 * (26 - i)
                upper_limit = 121.0 + 1.5 * (26 - i)
                x_value = 1.5 * (26 - i)
                L_eq[i] = self._loud_limits_400(self.freq_band_center[i], lower_limit, upper_limit, band_loudness, x_value)
            else:
                numerator = (160.0 - band_loudness) * np.log10(80.0)
                denominator = np.log10(self.freq_band_center[i])
                L_eq_B = 160.0 - numerator / denominator
                L_eq[i] = self._loud_limits_400(80.0, 86.5, 131.5, L_eq_B, 10.5)

        return L_eq

    @staticmethod
    def _loud_limits_400(
        f_central: float,
        lower_limit: float,
        upper_limit: float,
        loudness: np.ndarray | float,
        x_value: float,
    ) -> np.ndarray | float:
        """Apply the 400 Hz equivalent-loudness limiting transformation."""

        lower_equivalent = 115.0 - ((115.0 - loudness) * np.log10(400.0)) / np.log10(f_central)
        middle_equivalent = loudness - x_value
        upper_equivalent = 160.0 - ((160.0 - loudness) * np.log10(400.0)) / np.log10(f_central)
        equivalent = np.where(
            loudness <= lower_limit,
            lower_equivalent,
            np.where(loudness <= upper_limit, middle_equivalent, upper_equivalent),
        )
        return equivalent - 8.0

    def _calc_total_loudness(self, L_eq: np.ndarray) -> Tuple[float, np.ndarray]:
        """Calculate total loudness in sones from equivalent loudness values."""

        sones = self._sones_from_equivalent_loudness(L_eq)
        max_sones = float(np.max(sones))
        sum_factor = float(
            np.interp(
                max_sones,
                self.sones_table_indep,
                self.sum_factor_table,
                left=0.0,
                right=self.sum_factor_table[-1],
            )
        )
        total_loudness = max_sones + sum_factor * (float(np.sum(sones)) - max_sones)
        return total_loudness, sones

    def _load_or_require_signature(
        self,
        time: Optional[np.ndarray] = None,
        pressure: Optional[np.ndarray] = None,
        *,
        signature_file: Optional[str | Path] = None,
        header_lines: int = 0,
        delimiter: Optional[str] = None,
    ) -> None:
        if signature_file is not None:
            self.import_signature(signature_file, header_lines=header_lines, delimiter=delimiter)
        elif time is not None or pressure is not None:
            if time is None or pressure is None:
                raise ValueError("Both time and pressure must be supplied together.")
            self.set_signature(time, pressure)
        else:
            self._require_signature()

    def _prepare_working_signature(
        self,
        *,
        pad_front: Optional[int],
        pad_rear: Optional[int],
        len_window: Optional[int],
    ) -> None:
        pad_front, pad_rear, len_window = self._resolve_preprocessing_settings(
            pad_front=pad_front,
            pad_rear=pad_rear,
            len_window=len_window,
        )
        self._reset_working_signature()
        if len_window:
            self.window(len_window)
        self.padding(n_front_points=self.n_data_points * pad_front, n_rear_points=self.n_data_points * pad_rear)

    def _run_mark_vii(self) -> float:
        self.frequency_hz, self.power_spectrum = self._power_spectrum()
        self.band_energy, self.sound_pressure_level = self._sound_pressure_levels(
            self.frequency_hz,
            self.power_spectrum,
        )
        self.equivalent_loudness = self._equivalent_loudness(self.sound_pressure_level)
        self.total_loudness_sones, self.sones = self._calc_total_loudness(self.equivalent_loudness)
        self.perceived_loudness_pldb = float(32.0 + 9.0 * np.log2(self.total_loudness_sones))
        return self.perceived_loudness_pldb

    def _build_loudness_results(
        self,
        *,
        pldb: float,
        ctl: Optional[float],
        a_star: Optional[float],
        growth: float,
        day_loudness,
        night_loudness,
        equivalent_loudnesses,
    ) -> LoudnessResults:
        if ctl is None and a_star is not None:
            community_tolerance_level = float(-10.0 * np.log10(-np.log(0.5)) / growth + a_star / growth)
        else:
            community_tolerance_level = ctl

        return LoudnessResults(
            pldb=pldb,
            ctl=float(fidell_ctl(pldb, growth=growth, ctl=ctl, a_star=a_star)),
            community_tolerance_level=community_tolerance_level,
            dnl=dnl(day_loudness, night_loudness),
            equivalent_loudness=equivalent(equivalent_loudnesses),
            alphabet_weighted_loudnesses=alphabet_weighted_levels(self.freq_band_center, self.sound_pressure_level),
        )

    def _sound_pressure_level_from_energy(self, energy: np.ndarray) -> np.ndarray:
        with np.errstate(divide="ignore", invalid="ignore"):
            return 10.0 * np.log10(energy / (self.ref_pressure_psf**2)) - 3.0

    def _sones_from_equivalent_loudness(self, equivalent_loudness: np.ndarray) -> np.ndarray:
        return np.interp(
            equivalent_loudness,
            self.equiv_loudness_table_indep,
            self.sones_equiv_loudness_table,
            left=0.0,
            right=self.sones_equiv_loudness_table[-1],
        )

    @staticmethod
    def _pldb_from_sones(sones: np.ndarray) -> np.ndarray:
        with np.errstate(divide="ignore", invalid="ignore"):
            pldb = 32.0 + 9.0 * np.log2(sones)
        return np.where(sones > 0.0, pldb, 0.0)

    @staticmethod
    def _calibrate_local_energy(
        raw_energy: np.ndarray,
        time_s: np.ndarray,
        expected_energy: np.ndarray,
    ) -> np.ndarray:
        local_energy = np.zeros_like(raw_energy)
        recovered_energy = np.trapz(raw_energy, x=time_s, axis=1)
        valid = (
            (expected_energy > 0.0)
            & np.isfinite(expected_energy)
            & (recovered_energy > 0.0)
            & np.isfinite(recovered_energy)
        )
        local_energy[valid] = raw_energy[valid] * (expected_energy[valid] / recovered_energy[valid])[:, np.newaxis]
        return local_energy

    def _resolve_preprocessing_settings(
        self,
        *,
        pad_front: Optional[int],
        pad_rear: Optional[int],
        len_window: Optional[int],
    ) -> Tuple[int, int, int]:
        if pad_front is not None or pad_rear is not None or len_window is not None:
            self.configure(pad_front=pad_front, pad_rear=pad_rear, len_window=len_window)
        return self.pad_front, self.pad_rear, self.len_window

    def _wavelet_local_energy(self, morlet_w: float = 6.0) -> np.ndarray:
        """Return uncalibrated Morlet CWT local energy by Mark VII band."""

        self._require_signature()
        if self.dt_s is None:
            raise RuntimeError("Signal time step is not available.")

        sampling_frequency_hz = 1.0 / self.dt_s
        widths = morlet_w * sampling_frequency_hz / (2.0 * np.pi * self.freq_band_center)
        coefficients = signal.cwt(
            self.sig_pressure_psf,
            lambda points, width: signal.morlet2(points, width, w=morlet_w),
            widths,
        )
        return np.abs(coefficients) ** 2

    def _top_sensitivity_buckets(
        self,
        time_s: np.ndarray,
        local_energy: np.ndarray,
        sone_map: np.ndarray,
        local_pldb: np.ndarray,
        top_n: int,
    ) -> Tuple[Dict[str, float], ...]:
        if top_n == 0:
            return tuple()

        scores = np.nan_to_num(sone_map, nan=0.0, posinf=0.0, neginf=0.0)
        flat_order = np.argsort(scores, axis=None)[::-1]
        buckets = []

        for flat_index in flat_order:
            if len(buckets) >= top_n:
                break
            band_index, time_index = np.unravel_index(flat_index, scores.shape)
            score = float(scores[band_index, time_index])
            if score <= 0.0:
                break
            buckets.append(
                {
                    "band_index": int(band_index),
                    "time_index": int(time_index),
                    "band_center_hz": float(self.freq_band_center[band_index]),
                    "time_s": float(time_s[time_index]),
                    "local_energy": float(local_energy[band_index, time_index]),
                    "local_sones": score,
                    "local_pldb": float(local_pldb[band_index, time_index]),
                    "score": score,
                }
            )

        return tuple(buckets)

    def _require_signature(self) -> None:
        if self.sig_time_ms is None or self.sig_pressure_psf is None:
            raise RuntimeError("No pressure signature has been loaded.")

    def _require_pressure(self) -> None:
        if self.sig_pressure_psf is None:
            raise RuntimeError("No pressure signature has been loaded.")

    def _reset_working_signature(self) -> None:
        if self._source_time_ms is None or self._source_pressure_psf is None:
            return

        self.sig_time_ms = self._source_time_ms.copy()
        self.sig_pressure_psf = self._source_pressure_psf.copy()
        self.dt_ms = float(self.sig_time_ms[1] - self.sig_time_ms[0])
        self.dt_s = self.dt_ms * 1.0e-3
        self.freq_s = 1.0 / self.dt_s
        self.n_data_points = len(self.sig_pressure_psf)
        self.windowed_signal = False
        self.clear_results()


def import_sig(filename: str | Path, header_lines: int = 0, delimiter: Optional[str] = None) -> Tuple[np.ndarray, np.ndarray]:
    r"""Import time and pressure data from a file.

    Any file type that is compatible with :func:`numpy.genfromtxt` can be used
    with this function. The time data should be contained in the left-most
    column of the file, and the pressure data should be contained in the next
    column. Header lines should be skipped using the ``header_lines`` parameter.

    Parameters
    ----------
    filename : str or pathlib.Path
        File from which the time and pressure data will be imported.
    header_lines : int, optional
        Number of header lines to skip before reading numeric data.
    delimiter : str, optional
        Delimiter passed to :func:`numpy.genfromtxt`.

    Returns
    -------
    time : numpy.ndarray
        Time data imported from the file.
    pressure : numpy.ndarray
        Pressure data imported from the file.
    """

    calculator = PyLdB()
    calculator.import_signature(filename, header_lines=header_lines, delimiter=delimiter)
    return calculator.sig_time_ms.copy(), calculator.sig_pressure_psf.copy()


def perceivedloudness(
    time: np.ndarray,
    pressure: np.ndarray,
    *,
    pad_front: int = 1,
    pad_rear: int = 1,
    len_window: int = 800,
    print_results: bool = False,
) -> float:
    """Backward-compatible function wrapper around :class:`PyLdB`.

    New code should prefer creating a :class:`PyLdB` instance and calling
    :meth:`PyLdB.perceived_loudness` or :meth:`PyLdB.calculate`.
    """

    return PyLdB(time=time, pressure=pressure).perceived_loudness(
        pad_front=pad_front,
        pad_rear=pad_rear,
        len_window=len_window,
        print_results=print_results,
    )


__all__ = ["LoudnessResults", "SensitivityResults", "PyLdB", "import_sig", "perceivedloudness"]
