# -*- coding: utf-8 -*-
"""A perceived loudness (PLdB) calculator.

PyLdB implements Stevens' Mark VII procedure for the calculation of the
perceived loudness of a pressure signature.

Routine Listings
-----------------
PerceivedLoudness(time, pressure[, pad_f, pad_r, len_window])
Main routine. Calculates and displays perceived loudness in PLdB.

_window(dataset, len_window)     Applies a Hanning window to a dataset.

_padding(x_var, y_var, f_pad, r_pad)     Applies zero padding to the front and
                                         rear of a dataset with lengths of
                                         f_pad and r_pad respectively.
_power_spectrum(time, pressure)      Performs an FFT on the pressure signature
                                     and generates a one-sided power spectrum.

_power_interp(freq, power, N)     Interpolates power data to match frequency
                                  band boundaries.

_sound_pressure_levels(freq, power, n_bins)     Calculates the sound pressure
                                                level of each frequency band.

_equivalent_loudness(L, n_bins)     Calculates equivalent loudness values.

_loud_limits_400(f_central, lower_limit, upper_limit, loudness, X)
Chooses an appropriate equivalent loudness transformation according to dB
limits given in Stevens' methodology.

_calc_total_loudness(L_eq)    Uses table values to look up and interpolate a
                              summation factor and value in sones to calculate
                              a total loudness value in sones for a signature.

See Also
--------
numpy.interp : Linear interpolation for lists
numpy.hanning : Calculates a Hanning window given a number of points
numpy.pad : Zero-pads a list
numpy.fft.fft : Fast Fourier transform (FFT) routine
numpy.fft.fftfreq : Generates frequency range for FFT
numpy.argsort : Returns indices to sort an array
numpy.nonzero : Returns non-zero elements in an array subject to conditions
scipy.integrate.trapz : Performs trapezoidal numerical integration

Notes
------
The pyldb module utilizes the Mark VII procedure for the calculation of
perceived loudness created by Stevens. The procedure works by first importing
time and pressure data which is windowed and zero-padded prior to performing
a frequency analysis via an FFT. From the frequency analysis, a one-sided
power spectrum is created, which allows for the calculation of the energy
contained in one-third octave frequency bands for the pressure signature. The
energy is found by integrating the power spectrum using a trapezoidal rule.
This energy can be transformed into a sound pressure level measured in decibels
for each of the frequency bands. The sound pressure levels are then converted
to an equivalent loudness value using equal-sone contours generated by Stevens.
Using data tabulated by Stevens, a total loudness in units of sones is
calculated, which is then transformed into perceived loudness using a power law
developed by Stevens.

References
-----------
Stevens, S., “Perceived level of noise by Mark VII and decibels (E),”
The Journal of the Acoustical Society of America, Vol. 51,No. 2B, 1972,
pp. 575–601.

Jackson, G., and Leventhall, H., “Calculation of the perceived level of noise
(PLdB) using Stevens’ method (Mark VII),” Applied Acoustics, Vol. 6, No. 1,
1973, pp. 23–34.

Shepherd, K. P., and Sullivan, B. M., “A loudness calculation procedure
applied to shaped sonic booms,” 1991.

Johnson, D., and Robinson, D., “Procedure for calculating the loudness of
sonic bangs,” Acta Acustica united with Acustica, Vol. 21, No. 6, 1969,
pp. 307–318.

Example
--------
import pyldb
import numpy as np

time = np.arange(0,4*np.pi,0.01) # Any time array in miliseconds
pressure = 0.04*np.cos(time) # Any pressure array in lbs/ft^2 (psf)

PLdB = pyldb.perceivedloudness(time, pressure, pad_front=5, pad_rear=5,
                               len_window=1000)
print(PLdB)

"""

import numpy as np
import scipy.integrate as integrate
import os

class PyLdB:
    
    def __init__(self):
        self._initialize_table_data()
        self.ref_pressure_psf = 2.900755e-9*144  # Reference pressure in psf (20 µPa)
        self.ref_time_s = 0.07  # Human auditory response time time in seconds   

    def perceivedloudness(self, time, pressure,
                        pad_front=1, pad_rear=1,
                        len_window=800, print_results=False):
        r"""Calculates the perceived loudness using time and pressure values in
        miliseconds and lb/ft^2 (psf) respectively.

        This function encapsulates all of the calculation steps to return a
        perceived loudness value given two arrays for time and pressure. The
        pressure signature is first windowed using a Hanning window to ensure
        a complete cycle can be formed for use in a fast Fourier transform (FFT).
        Next, the time and pressure arrays are zero-padded to increase the
        resolution of the FFT output.

        Using the windowed and zero-padded pressure and time arrays, a one-sided
        power spectrum is produced. The energy in the power spectrum can then be
        calculated using a trapezoidal rule numerical integration algorithm.
        The energy is then used to find a sound pressure level in decibels for
        one-third octave frequency bands (stored as global constants).

        Stevens' Mark VII algorithm then transforms the sound pressure levels for
        each of the frequency bands into an equivalent loudness value with a 3150
        Hz reference frequency. The equivalent loudness values are then used with a
        table for conversion from decibels to sones (stored as a global constant).
        A summation parameter is likewise found using tabulated data from Stevens.
        Finally, a summation rule is used to find the total loudness, which is
        used alongside a power-rule to calculate the perceived loudness in PLdB.

        Parameters
        ----------
        time : array_like
            An array containing a time signature to be used in the calculation of
            the perceived loudness. This array should be sampled at a constant
            frequency. It should have the same number of points and the same
            spacing as the `pressure` parameter.
        pressure : array_like
            An array containing a pressure signature to be used in the calculation
            of the perceived loudness. This array should be sampled at a constant
            frequency. It should have the same number of points and the same
            spacing as the `time` parameter.
        pad_front : int, optional
            Defaults to 1. This parameter specifies the length of the zero-padding
            that will be applied to the font of the `time` and `pressure` arrays.
            For example, if `pad_front`=10, the length of the array of zeros added
            to the front of the `time` and `pressure` arrays will be equal to 10x
            the length of the `time` and `pressure` arrays.
        pad_rear : int, optional
            Defaults to 1. This parameter specifies the length of the zero-padding
            that will be applied to the font of the `time` and `pressure` arrays.
            For example, if `pad_front`=10, the length of the array of zeros added
            to the front of the `time` and `pressure` arrays will be equal to 10x
            the length of the `time` and `pressure` arrays.
        len_window : int, optional
            Defaults to 800 points. This parameter specifies the number of points
            over which the Hanning window will be applied on both the front and the
            rear of the signal. In other words, the front 800 points of the
            'pressure' array will be windowed with the first 800 points of a 1600
            point Hanning window, and the last 800 points of the `pressure` array
            will be windowed with the last 800 points of a 1600 point Hanning
            window.
        print_results : bool, optional
            Defaults to False. This parameter acts as a flag to output several
            meaningful results from the analysis performed by PyLdB. The results
            printed include the padded and windowed signature passed into the
            loudness calculator as well as the power spectrum of the signature, and
            the sound pressure level, equivalent loudness, and sone values
            associated with each frequency band. These results are placed in a
            directory called `PyLdB_Results` and are useful for analysis of the
            signature.

        Returns
        -------
        pldb : float
            Value for perceived loudness in units of PLdB.

        Examples
        --------
        These are written in doctest format, and should illustrate how to
        use the function.

        >>> import pyldb
        >>> import numpy as np
        >>> time = np.linspace(0,100,num=10000) # Any time array in miliseconds
        >>> pressure = np.linspace(0,100,num=10000) # Any pressure array in psf
        >>> PLdB = pyldb.perceivedloudness(time, pressure, pad_front=4,pad_rear=4,
                                        len_window=1000)
        >>> print PLdB
        """
        # Initialize variables
        n_bins = len(self.freq_band_center)
        n_frontpad = len(pressure)*pad_front
        n_rearpad = len(pressure)*pad_rear

        # Begin main PLdB calculation method
        if len_window != 0:
            pressure_window = _window(pressure, len_window)
        else:
            pressure_window = pressure
        time_pad, pressure_pad = _padding(time, pressure_window, n_frontpad,
                                        n_rearpad)
        freq, power = _power_spectrum(time_pad, pressure_pad)
        energy, loudness = _sound_pressure_levels(freq, power, n_bins)
        L_eq = _equivalent_loudness(loudness, n_bins)
        total_loudness, sones = _calc_total_loudness(L_eq)
        pldb = 32.0 + 9.0*np.log2(total_loudness)

        # Prints relevant results from the loudness analysis
        if print_results:
            directory = './PyLdB_Results'
            if not os.path.exists(directory):
                os.makedirs(directory)
            np.savetxt(directory + '/final_sig',
                    np.array([time_pad, pressure_pad]).T)
            np.savetxt(directory + '/power_spec',
                    np.array([freq, power]).T)
            np.savetxt(directory + '/sound_pressure_levels',
                    np.array([BAND_CENTERS, loudness]).T)
            np.savetxt(directory + '/equivalent_loudness',
                    np.array([BAND_CENTERS, L_eq]).T)
            np.savetxt(directory + '/sones',
                    np.array([BAND_CENTERS, sones]).T)
        return pldb

    def window(self, len_window):
        win = np.hanning(len_window*2)
        self.sig_pressure_psf[:len_window] *= win[:len_window]
        self.sig_pressure_psf[-len_window:] *= win[len_window:]


    def padding(self, n_pad_points):
        padded_pressure = np.pad(self.sig_pressure_psf, n_pad_points, 'constant')
        init_time_f = 0.0
        final_time_f = (n_pad_points - 1)*self.dt_ms
        init_time_r = final_time_f + self.sig_time_ms[-1] + 2.0*self.dt_ms
        final_time_r = init_time_r + (n_pad_points - 1)*self.dt_ms
        time_range_f = np.arange(init_time_f, final_time_f + self.dt_ms, self.dt_ms)
        time_range_r = np.arange(init_time_r, final_time_r + self.dt_ms, self.dt_ms)
        padded_time = np.concatenate((time_range_f, self.sig_time_ms + final_time_f + self.dt_ms,
                                    time_range_r))
        self.sig_pressure_psf = padded_pressure
        self.sig_time_ms = padded_time
        self.n_data_points = len(self.sig_pressure_psf)


    def _power_spectrum(self, time, pressure):
        # The units for time are in milliseconds, and the units for pressure
        # are lbs/ft^2 (psf).
        dt_s = self.dt_ms*(10**-3)  # ms -> s
        FFT = np.fft.hfft(self.sig_pressure_psf)
        freq = np.fft.fftfreq(N)/dt
        Power = (np.abs(FFT)**2)*(dt**2)
        freqOne, PowerOne = _power_interp(freq, Power, N)
        return freqOne, PowerOne


    def _power_interp(freq, power, N):
        # Convert double sided Power Spectrum to single sided
        freq_one_side = np.copy(freq[0:N//2])
        power[1:N//2] = 2.*power[1:N//2]
        power_one_side = np.copy(power[0:N//2])

        # Interpolate values corresponding to band limits
        interp_freq = np.append(BAND_LOWER_LIMITS, BAND_UPPER_LIMITS[-1])
        interp_power = np.interp(interp_freq, freq_one_side, power_one_side)
        original_pow_freq = np.array([freq_one_side, power_one_side])
        interp_pow_freq = np.array([interp_freq, interp_power])
        full_pow_freq = np.concatenate((original_pow_freq, interp_pow_freq),
                                    axis=1)
        full_pow_freq_sort = np.argsort(full_pow_freq[0])
        freq_one = full_pow_freq[0, full_pow_freq_sort]
        power_one = full_pow_freq[1, full_pow_freq_sort]
        return freq_one, power_one


    def _sound_pressure_levels(freq, power, n_bins):
        po = (2.900755e-9)*144  # psi -> psf
        t_crit = 0.07
        energy = np.zeros(n_bins)
        for j in range(n_bins):
            i_section = np.nonzero((BAND_LOWER_LIMITS[j] <= freq)
                                & (freq <= BAND_UPPER_LIMITS[j]))[0]
            if len(i_section) != 0:
                power_section = power[i_section]
                frequency_section = freq[i_section]
                energy[j] = integrate.trapz(power_section, x=frequency_section)
        energy /= t_crit
        loudness = 10*np.log10(energy/(po**2)) - 3
        return energy, loudness


    def _equivalent_loudness(L, n_bins):
        L_eq = np.zeros(n_bins)
        for i in range(n_bins):
            if i > 39:
                L_eq[i] = L[i] + 4.*(39. - i)
            if 35 <= i <= 39:
                L_eq[i] = L[i]
            if 32 <= i <= 34:
                L_eq[i] = L[i] - 2.*(35. - i)
            if 26 < i <= 31:
                L_eq[i] = L[i] - 8.0
            if 20 <= i <= 26:
                if i == 26:
                    L_eq[i] = _loud_limits_400(BAND_CENTERS[i],
                                            76.0, 121.0, L[i], 0.0)
                if i == 25:
                    L_eq[i] = _loud_limits_400(BAND_CENTERS[i],
                                            77.5, 122.5, L[i], 1.5)
                if i == 24:
                    L_eq[i] = _loud_limits_400(BAND_CENTERS[i],
                                            79.0, 124.0, L[i], 3.0)
                if i == 23:
                    L_eq[i] = _loud_limits_400(BAND_CENTERS[i],
                                            80.5, 125.5, L[i], 4.5)
                if i == 22:
                    L_eq[i] = _loud_limits_400(BAND_CENTERS[i],
                                            82.0, 127.0, L[i], 6.0)
                if i == 21:
                    L_eq[i] = _loud_limits_400(BAND_CENTERS[i],
                                            83.5, 128.5, L[i], 7.5)
                if i == 20:
                    L_eq[i] = _loud_limits_400(BAND_CENTERS[i],
                                            85.0, 130.0, L[i], 9.0)
            if i <= 19:
                numerator = ((160.0 - L[i])*np.log10(80.0))
                denominator = np.log10(BAND_CENTERS[i])
                L_eq_B = 160.0 - numerator/denominator
                L_eq[i] = _loud_limits_400(80.0, 86.5, 131.5, L_eq_B, 10.5)
        return L_eq


    def _loud_limits_400(f_central, lower_limit, upper_limit, loudness, X):
        if loudness <= lower_limit:
            A = 115.0 - ((115.0-loudness)*np.log10(400.0))/np.log10(f_central)
            L_eq = A - 8.0
        if lower_limit < loudness <= upper_limit:
            L_eq = loudness - X - 8.0
        if loudness > upper_limit:
            A = 160.0 - ((160.0 - loudness)*np.log10(400.0))/np.log10(f_central)
            L_eq = A - 8.0
        return L_eq


    def _calc_total_loudness(L_eq):
        sones = np.interp(L_eq, L_EQ_RANGE, SONES_L, left=0.0, right=SONES_L[-1])
        sum_f_max = np.interp(sones.max(), SONES_F, SUMMATION_FACTORS,
                            left=0.0, right=SUMMATION_FACTORS[-1])
        total_loudness = sones.max() + sum_f_max*(sum(sones) - sones.max())
        return total_loudness, sones
    
    def _initialize_table_data(self):
        # Get the absolute path of the directory containing this script
        base_dir = os.path.dirname(os.path.abspath(__file__))
        tables_dir = os.path.join(base_dir, '../tables')

        # Use absolute paths to load the tables
        self.equiv_loudness_sones_data = np.genfromtxt(
            os.path.join(tables_dir, 'L_eq_v_sones.csv'), delimiter=',', skip_header=1
        )
        self.equiv_loudness_table_indep = self.equiv_loudness_sones_data[:, 0]
        self.sones_equiv_loudness_table = self.equiv_loudness_sones_data[:, 1]
        self.num_equiv_loudness_vals = len(self.equiv_loudness_table_indep)

        self.sones_sum_factor_data = np.genfromtxt(
            os.path.join(tables_dir, 'sones_v_sumf.csv'), delimiter=',', skip_header=1
        )
        self.sones_table_indep = self.sones_sum_factor_data[:, 0]
        self.sum_factor_table = self.sones_sum_factor_data[:, 1]
        self.num_sum_factors = len(self.sones_table_indep)

        self.freq_band_data = np.genfromtxt(
            os.path.join(tables_dir, 'freq_bands.csv'), delimiter=',', skip_header=1
        )
        self.freq_band_center = self.freq_band_data[:, 0]
        self.freq_band_lower_lim = self.freq_band_data[:, 1]
        self.freq_band_upper_lim = self.freq_band_data[:, 2]
        self.num_freq_bands = len(self.freq_band_center)
    
    def _import_sig(self, filename, header_lines=0, delimiter=None):
        sig_data = np.genfromtxt(filename, skip_header=header_lines,
                                delimiter=delimiter)
        self.sig_time_ms = sig_data[:, 0]
        self.sig_pressure_psf = sig_data[:, 1]
        self.dt_ms = (self.sig_time_ms[1] - self.sig_time_ms[0])  # Time step in ms
        self.n_data_points = len(self.sig_pressure_psf)

if __name__ == "__main__":
    pldb = PyLdB()
